### ISSUE TITLE
Question about code splitting on server side

### ISSUE THREAD

**Issue by saniko** [5tefan/universal-react-demo#6]
in app/routes/About/index.js 
the comment say:
 
> // Don't code split w/ System.import for server side render

Could you please explain why we don't need this?
Don't we need to server side render that part of the app?

**Comment by 5tefan** [comment]
`System.import` is undefined server side. The use of `System.import` is intended for chunking so that the user doesn't have to download the entire js application on their first page load, instead we have `System.import` in the router definition which initiates a request for the relevant piece of the application when needed.

This doesn't make sense server side since the code is already there - so server side we skip the promise/resolve normally done by `System.import` (it's undefined anyway, but you could polyfill, see [1]) and instead just use a native require.

The application would still work if instead of:
```javascript
if (ONSERVER) {
    cb(null, require('./components/About.jsx'));
} else {
    System.import('./components/About.jsx')
        .then((About) => cb(null, About));
}
```
we just had
```javascript
cb(null, require('./components/About.jsx'));
```
except, we would loose chunking on the client side and the About component would just get bundled into the main entrypoint.

[1] http://stackoverflow.com/a/39088208
